/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include "cparser.h"
#include "cparser_priv.h"
#include "cparser_token.h"
#include "cparser_tree.h"

cparser_result_t
cparser_glue_show_employees (cparser_t *parser)
{
    cparser_cmd_show_employees(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_employees_all (cparser_t *parser)
{
    cparser_cmd_show_employees_all(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_employees_by_id_min_max (cparser_t *parser)
{
    uint32_t min_val;
    uint32_t *min_ptr = NULL;
    uint32_t max_val;
    uint32_t *max_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[2], &min_val);
    assert(CPARSER_OK == rc);
    min_ptr = &min_val;
    rc = cparser_get_uint(&parser->tokens[3], &max_val);
    if (CPARSER_OK == rc) {
        max_ptr = &max_val;
    } else {
        assert(4 > parser->token_tos);
    }
    cparser_cmd_show_employees_by_id_min_max(&parser->context,
        min_ptr,
        max_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_employee_id (cparser_t *parser)
{
    uint32_t id_val;
    uint32_t *id_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_hex(&parser->tokens[1], &id_val);
    assert(CPARSER_OK == rc);
    id_ptr = &id_val;
    cparser_cmd_employee_id(&parser->context,
        id_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_emp_exit (cparser_t *parser)
{
    cparser_cmd_emp_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_emp_name_name (cparser_t *parser)
{
    char *name_val;
    char **name_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &name_val);
    assert(CPARSER_OK == rc);
    name_ptr = &name_val;
    cparser_cmd_emp_name_name(&parser->context,
        name_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_emp_date_of_birth_month_day_year (cparser_t *parser)
{
    int32_t month_val;
    int32_t *month_ptr = NULL;
    int32_t day_val;
    int32_t *day_ptr = NULL;
    int32_t year_val;
    int32_t *year_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_int(&parser->tokens[1], &month_val);
    assert(CPARSER_OK == rc);
    month_ptr = &month_val;
    rc = cparser_get_int(&parser->tokens[2], &day_val);
    assert(CPARSER_OK == rc);
    day_ptr = &day_val;
    rc = cparser_get_int(&parser->tokens[3], &year_val);
    assert(CPARSER_OK == rc);
    year_ptr = &year_val;
    cparser_cmd_emp_date_of_birth_month_day_year(&parser->context,
        month_ptr,
        day_ptr,
        year_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_emp_height_inches (cparser_t *parser)
{
    uint32_t inches_val;
    uint32_t *inches_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &inches_val);
    assert(CPARSER_OK == rc);
    inches_ptr = &inches_val;
    cparser_cmd_emp_height_inches(&parser->context,
        inches_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_emp_weight_lbs (cparser_t *parser)
{
    uint32_t lbs_val;
    uint32_t *lbs_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &lbs_val);
    assert(CPARSER_OK == rc);
    lbs_ptr = &lbs_val;
    cparser_cmd_emp_weight_lbs(&parser->context,
        lbs_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_emp_bonus_factor_scale (cparser_t *parser)
{
    double scale_val;
    double *scale_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_float(&parser->tokens[1], &scale_val);
    assert(CPARSER_OK == rc);
    scale_ptr = &scale_val;
    cparser_cmd_emp_bonus_factor_scale(&parser->context,
        scale_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_emp_pc_ip_address_ipv4 (cparser_t *parser)
{
    uint32_t ipv4_val;
    uint32_t *ipv4_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_ipv4addr(&parser->tokens[1], &ipv4_val);
    assert(CPARSER_OK == rc);
    ipv4_ptr = &ipv4_val;
    cparser_cmd_emp_pc_ip_address_ipv4(&parser->context,
        ipv4_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_emp_pc_mac_address_addr (cparser_t *parser)
{
    cparser_macaddr_t addr_val;
    cparser_macaddr_t *addr_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_macaddr(&parser->tokens[1], &addr_val);
    assert(CPARSER_OK == rc);
    addr_ptr = &addr_val;
    cparser_cmd_emp_pc_mac_address_addr(&parser->context,
        addr_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_emp_title_title (cparser_t *parser)
{
    char *title_val;
    char **title_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &title_val);
    assert(CPARSER_OK == rc);
    title_ptr = &title_val;
    cparser_cmd_emp_title_title(&parser->context,
        title_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_emp_help_filter (cparser_t *parser)
{
    char *filter_val;
    char **filter_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &filter_val);
    if (CPARSER_OK == rc) {
        filter_ptr = &filter_val;
    } else {
        assert(2 > parser->token_tos);
    }
    cparser_cmd_emp_help_filter(&parser->context,
        filter_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_no_employee_id (cparser_t *parser)
{
    uint32_t id_val;
    uint32_t *id_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_hex(&parser->tokens[2], &id_val);
    assert(CPARSER_OK == rc);
    id_ptr = &id_val;
    cparser_cmd_no_employee_id(&parser->context,
        id_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_save_roster_filename (cparser_t *parser)
{
    char *filename_val;
    char **filename_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[2], &filename_val);
    assert(CPARSER_OK == rc);
    filename_ptr = &filename_val;
    cparser_cmd_save_roster_filename(&parser->context,
        filename_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_load_roster_filename (cparser_t *parser)
{
    char *filename_val;
    char **filename_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_file(&parser->tokens[2], &filename_val);
    assert(CPARSER_OK == rc);
    filename_ptr = &filename_val;
    cparser_cmd_load_roster_filename(&parser->context,
        filename_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_help_filter (cparser_t *parser)
{
    char *filter_val;
    char **filter_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &filter_val);
    if (CPARSER_OK == rc) {
        filter_ptr = &filter_val;
    } else {
        assert(2 > parser->token_tos);
    }
    cparser_cmd_help_filter(&parser->context,
        filter_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_quit (cparser_t *parser)
{
    cparser_cmd_quit(&parser->context);
    return CPARSER_OK;
}

cparser_node_t cparser_node_quit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_quit,
    "Leave the database",
    NULL,
    NULL
};
cparser_node_t cparser_node_quit = {
    CPARSER_NODE_KEYWORD,
    0,
    "quit",
    NULL,
    NULL,
    &cparser_node_quit_eol
};
cparser_node_t cparser_node_help_filter_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_help_filter,
    "List all available commands with a substring 'filter' in it.",
    NULL,
    NULL
};
cparser_node_t cparser_node_help_filter = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:filter>",
    NULL,
    NULL,
    &cparser_node_help_filter_eol
};
cparser_node_t cparser_node_help_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_help_filter,
    NULL,
    &cparser_node_help_filter,
    NULL
};
cparser_node_t cparser_node_help = {
    CPARSER_NODE_KEYWORD,
    CPARSER_NODE_FLAGS_OPT_START,
    "help",
    NULL,
    &cparser_node_quit,
    &cparser_node_help_eol
};
cparser_node_t cparser_node_load_roster_filename_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_load_roster_filename,
    "Load roster file",
    NULL,
    NULL
};
cparser_node_t cparser_node_load_roster_filename = {
    CPARSER_NODE_FILE,
    0,
    "<FILE:filename>",
    NULL,
    NULL,
    &cparser_node_load_roster_filename_eol
};
cparser_node_t cparser_node_load_roster = {
    CPARSER_NODE_KEYWORD,
    0,
    "roster",
    NULL,
    NULL,
    &cparser_node_load_roster_filename
};
cparser_node_t cparser_node_load = {
    CPARSER_NODE_KEYWORD,
    0,
    "load",
    NULL,
    &cparser_node_help,
    &cparser_node_load_roster
};
cparser_node_t cparser_node_save_roster_filename_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_save_roster_filename,
    "Save the current roster to a file",
    NULL,
    NULL
};
cparser_node_t cparser_node_save_roster_filename = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:filename>",
    NULL,
    NULL,
    &cparser_node_save_roster_filename_eol
};
cparser_node_t cparser_node_save_roster = {
    CPARSER_NODE_KEYWORD,
    0,
    "roster",
    NULL,
    NULL,
    &cparser_node_save_roster_filename
};
cparser_node_t cparser_node_save = {
    CPARSER_NODE_KEYWORD,
    0,
    "save",
    NULL,
    &cparser_node_load,
    &cparser_node_save_roster
};
cparser_node_t cparser_node_no_employee_id_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_no_employee_id,
    "Delete an existing employee",
    NULL,
    NULL
};
cparser_node_t cparser_node_no_employee_id = {
    CPARSER_NODE_HEX,
    0,
    "<HEX:id>",
    NULL,
    NULL,
    &cparser_node_no_employee_id_eol
};
cparser_node_t cparser_node_no_employee = {
    CPARSER_NODE_KEYWORD,
    0,
    "employee",
    NULL,
    NULL,
    &cparser_node_no_employee_id
};
cparser_node_t cparser_node_no = {
    CPARSER_NODE_KEYWORD,
    0,
    "no",
    NULL,
    &cparser_node_save,
    &cparser_node_no_employee
};
cparser_node_t cparser_node_employee_id_root_help_filter_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_emp_help_filter,
    "List all available commands with a substring 'filter' in it.",
    NULL,
    NULL
};
cparser_node_t cparser_node_employee_id_root_help_filter = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:filter>",
    NULL,
    NULL,
    &cparser_node_employee_id_root_help_filter_eol
};
cparser_node_t cparser_node_employee_id_root_help_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_emp_help_filter,
    NULL,
    &cparser_node_employee_id_root_help_filter,
    NULL
};
cparser_node_t cparser_node_employee_id_root_help = {
    CPARSER_NODE_KEYWORD,
    CPARSER_NODE_FLAGS_OPT_START,
    "help",
    NULL,
    NULL,
    &cparser_node_employee_id_root_help_eol
};
cparser_node_t cparser_node_employee_id_root_title_title_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_emp_title_title,
    "Title",
    NULL,
    NULL
};
cparser_node_t cparser_node_employee_id_root_title_title = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:title>",
    NULL,
    NULL,
    &cparser_node_employee_id_root_title_title_eol
};
cparser_node_t cparser_node_employee_id_root_title = {
    CPARSER_NODE_KEYWORD,
    0,
    "title",
    NULL,
    &cparser_node_employee_id_root_help,
    &cparser_node_employee_id_root_title_title
};
cparser_node_t cparser_node_employee_id_root_pc_mac_address_addr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_emp_pc_mac_address_addr,
    "Employee's PC MAC address",
    NULL,
    NULL
};
cparser_node_t cparser_node_employee_id_root_pc_mac_address_addr = {
    CPARSER_NODE_MACADDR,
    0,
    "<MACADDR:addr>",
    NULL,
    NULL,
    &cparser_node_employee_id_root_pc_mac_address_addr_eol
};
cparser_node_t cparser_node_employee_id_root_pc_mac_address = {
    CPARSER_NODE_KEYWORD,
    0,
    "pc-mac-address",
    NULL,
    &cparser_node_employee_id_root_title,
    &cparser_node_employee_id_root_pc_mac_address_addr
};
cparser_node_t cparser_node_employee_id_root_pc_ip_address_ipv4_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_emp_pc_ip_address_ipv4,
    "Employee's PC IP address",
    NULL,
    NULL
};
cparser_node_t cparser_node_employee_id_root_pc_ip_address_ipv4 = {
    CPARSER_NODE_IPV4ADDR,
    0,
    "<IPV4ADDR:ipv4>",
    NULL,
    NULL,
    &cparser_node_employee_id_root_pc_ip_address_ipv4_eol
};
cparser_node_t cparser_node_employee_id_root_pc_ip_address = {
    CPARSER_NODE_KEYWORD,
    0,
    "pc-ip-address",
    NULL,
    &cparser_node_employee_id_root_pc_mac_address,
    &cparser_node_employee_id_root_pc_ip_address_ipv4
};
cparser_node_t cparser_node_employee_id_root_bonus_factor_scale_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_emp_bonus_factor_scale,
    "Scaling factor for bonus",
    NULL,
    NULL
};
cparser_node_t cparser_node_employee_id_root_bonus_factor_scale = {
    CPARSER_NODE_FLOAT,
    0,
    "<FLOAT:scale>",
    NULL,
    NULL,
    &cparser_node_employee_id_root_bonus_factor_scale_eol
};
cparser_node_t cparser_node_employee_id_root_bonus_factor = {
    CPARSER_NODE_KEYWORD,
    0,
    "bonus-factor",
    NULL,
    &cparser_node_employee_id_root_pc_ip_address,
    &cparser_node_employee_id_root_bonus_factor_scale
};
cparser_node_t cparser_node_employee_id_root_weight_lbs_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_emp_weight_lbs,
    "Weight in lbs",
    NULL,
    NULL
};
cparser_node_t cparser_node_employee_id_root_weight_lbs = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:lbs>",
    NULL,
    NULL,
    &cparser_node_employee_id_root_weight_lbs_eol
};
cparser_node_t cparser_node_employee_id_root_weight = {
    CPARSER_NODE_KEYWORD,
    0,
    "weight",
    NULL,
    &cparser_node_employee_id_root_bonus_factor,
    &cparser_node_employee_id_root_weight_lbs
};
cparser_node_t cparser_node_employee_id_root_height_inches_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_emp_height_inches,
    "Height in inches",
    NULL,
    NULL
};
cparser_node_t cparser_node_employee_id_root_height_inches = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:inches>",
    NULL,
    NULL,
    &cparser_node_employee_id_root_height_inches_eol
};
cparser_node_t cparser_node_employee_id_root_height = {
    CPARSER_NODE_KEYWORD,
    0,
    "height",
    NULL,
    &cparser_node_employee_id_root_weight,
    &cparser_node_employee_id_root_height_inches
};
cparser_node_t cparser_node_employee_id_root_date_of_birth_month_day_year_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_emp_date_of_birth_month_day_year,
    "Date of birth",
    NULL,
    NULL
};
cparser_node_t cparser_node_employee_id_root_date_of_birth_month_day_year = {
    CPARSER_NODE_INT,
    0,
    "<INT:year>",
    NULL,
    NULL,
    &cparser_node_employee_id_root_date_of_birth_month_day_year_eol
};
cparser_node_t cparser_node_employee_id_root_date_of_birth_month_day = {
    CPARSER_NODE_INT,
    0,
    "<INT:day>",
    NULL,
    NULL,
    &cparser_node_employee_id_root_date_of_birth_month_day_year
};
cparser_node_t cparser_node_employee_id_root_date_of_birth_month = {
    CPARSER_NODE_INT,
    0,
    "<INT:month>",
    NULL,
    NULL,
    &cparser_node_employee_id_root_date_of_birth_month_day
};
cparser_node_t cparser_node_employee_id_root_date_of_birth = {
    CPARSER_NODE_KEYWORD,
    0,
    "date-of-birth",
    NULL,
    &cparser_node_employee_id_root_height,
    &cparser_node_employee_id_root_date_of_birth_month
};
cparser_node_t cparser_node_employee_id_root_name_name_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_emp_name_name,
    "Name",
    NULL,
    NULL
};
cparser_node_t cparser_node_employee_id_root_name_name = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:name>",
    NULL,
    NULL,
    &cparser_node_employee_id_root_name_name_eol
};
cparser_node_t cparser_node_employee_id_root_name = {
    CPARSER_NODE_KEYWORD,
    0,
    "name",
    NULL,
    &cparser_node_employee_id_root_date_of_birth,
    &cparser_node_employee_id_root_name_name
};
cparser_node_t cparser_node_employee_id_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_emp_exit,
    "Exit employee submode",
    NULL,
    NULL
};
cparser_node_t cparser_node_employee_id_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    NULL,
    &cparser_node_employee_id_root_name,
    &cparser_node_employee_id_root_exit_eol
};
cparser_node_t cparser_node_employee_id_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode emp",
    NULL,
    &cparser_node_employee_id_root_exit
};
cparser_node_t cparser_node_employee_id_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_employee_id,
    "Add a new employee or enter the record of an existing employee",
    NULL,
    &cparser_node_employee_id_root
};
cparser_node_t cparser_node_employee_id = {
    CPARSER_NODE_HEX,
    0,
    "<HEX:id>",
    NULL,
    NULL,
    &cparser_node_employee_id_eol
};
cparser_node_t cparser_node_employee = {
    CPARSER_NODE_KEYWORD,
    0,
    "employee",
    NULL,
    &cparser_node_no,
    &cparser_node_employee_id
};
cparser_node_t cparser_node_show_employees_by_id_min_max_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_employees_by_id_min_max,
    "List all employees within a certain range of employee ids",
    NULL,
    NULL
};
cparser_node_t cparser_node_show_employees_by_id_min_max = {
    CPARSER_NODE_UINT,
    CPARSER_NODE_FLAGS_OPT_END,
    "<UINT:max>",
    NULL,
    NULL,
    &cparser_node_show_employees_by_id_min_max_eol
};
cparser_node_t cparser_node_show_employees_by_id_min_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_show_employees_by_id_min_max,
    NULL,
    &cparser_node_show_employees_by_id_min_max,
    NULL
};
cparser_node_t cparser_node_show_employees_by_id_min = {
    CPARSER_NODE_UINT,
    CPARSER_NODE_FLAGS_OPT_START,
    "<UINT:min>",
    NULL,
    NULL,
    &cparser_node_show_employees_by_id_min_eol
};
cparser_node_t cparser_node_show_employees_by_id = {
    CPARSER_NODE_KEYWORD,
    0,
    "employees-by-id",
    NULL,
    NULL,
    &cparser_node_show_employees_by_id_min
};
cparser_node_t cparser_node_show_employees_all_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_employees_all,
    "List detail records of all employees.",
    NULL,
    NULL
};
cparser_node_t cparser_node_show_employees_all = {
    CPARSER_NODE_KEYWORD,
    0,
    "all",
    NULL,
    NULL,
    &cparser_node_show_employees_all_eol
};
cparser_node_t cparser_node_show_employees_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_employees,
    "List a summary of employees.",
    &cparser_node_show_employees_all,
    NULL
};
cparser_node_t cparser_node_show_employees = {
    CPARSER_NODE_KEYWORD,
    0,
    "employees",
    NULL,
    &cparser_node_show_employees_by_id,
    &cparser_node_show_employees_eol
};
cparser_node_t cparser_node_show = {
    CPARSER_NODE_KEYWORD,
    0,
    "show",
    NULL,
    &cparser_node_employee,
    &cparser_node_show_employees
};
cparser_node_t cparser_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root node of the parser tree",
    NULL,
    &cparser_node_show
};
