/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include "cparser.h"
#include "cparser_priv.h"
#include "cparser_token.h"
#include "cparser_tree.h"

cparser_result_t
cparser_glue_show_registers (cparser_t *parser)
{
    cparser_cmd_show_registers(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_registers_crtc (cparser_t *parser)
{
    cparser_cmd_show_registers_crtc(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_registers_ga (cparser_t *parser)
{
    cparser_cmd_show_registers_ga(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_registers_z80 (cparser_t *parser)
{
    cparser_cmd_show_registers_z80(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_breakpoints_add_adress (cparser_t *parser)
{
    uint32_t adress_val;
    uint32_t *adress_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_hex(&parser->tokens[2], &adress_val);
    assert(CPARSER_OK == rc);
    adress_ptr = &adress_val;
    cparser_cmd_breakpoints_add_adress(&parser->context,
        adress_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_breakpoints_remove_adress (cparser_t *parser)
{
    uint32_t adress_val;
    uint32_t *adress_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_hex(&parser->tokens[2], &adress_val);
    assert(CPARSER_OK == rc);
    adress_ptr = &adress_val;
    cparser_cmd_breakpoints_remove_adress(&parser->context,
        adress_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_breakpoints_list (cparser_t *parser)
{
    cparser_cmd_breakpoints_list(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_video_color_on (cparser_t *parser)
{
    cparser_cmd_video_color_on(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_video_color_gray (cparser_t *parser)
{
    cparser_cmd_video_color_gray(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_video_color_green (cparser_t *parser)
{
    cparser_cmd_video_color_green(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_quit (cparser_t *parser)
{
    cparser_cmd_quit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_reset (cparser_t *parser)
{
    cparser_cmd_reset(&parser->context);
    return CPARSER_OK;
}

cparser_node_t cparser_node_reset_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_reset,
    "Reset emu",
    NULL,
    NULL
};
cparser_node_t cparser_node_reset = {
    CPARSER_NODE_KEYWORD,
    0,
    "reset",
    NULL,
    NULL,
    &cparser_node_reset_eol
};
cparser_node_t cparser_node_quit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_quit,
    "Quit Caprice",
    NULL,
    NULL
};
cparser_node_t cparser_node_quit = {
    CPARSER_NODE_KEYWORD,
    0,
    "quit",
    NULL,
    &cparser_node_reset,
    &cparser_node_quit_eol
};
cparser_node_t cparser_node_video_color_green_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_video_color_green,
    "put screen in greenscale",
    NULL,
    NULL
};
cparser_node_t cparser_node_video_color_green = {
    CPARSER_NODE_KEYWORD,
    0,
    "green",
    NULL,
    NULL,
    &cparser_node_video_color_green_eol
};
cparser_node_t cparser_node_video_color_gray_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_video_color_gray,
    "put screen in grayscale",
    NULL,
    NULL
};
cparser_node_t cparser_node_video_color_gray = {
    CPARSER_NODE_KEYWORD,
    0,
    "gray",
    NULL,
    &cparser_node_video_color_green,
    &cparser_node_video_color_gray_eol
};
cparser_node_t cparser_node_video_color_on_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_video_color_on,
    "put screen in color ",
    NULL,
    NULL
};
cparser_node_t cparser_node_video_color_on = {
    CPARSER_NODE_KEYWORD,
    0,
    "on",
    NULL,
    &cparser_node_video_color_gray,
    &cparser_node_video_color_on_eol
};
cparser_node_t cparser_node_video_color = {
    CPARSER_NODE_KEYWORD,
    0,
    "color",
    NULL,
    NULL,
    &cparser_node_video_color_on
};
cparser_node_t cparser_node_video = {
    CPARSER_NODE_KEYWORD,
    0,
    "video",
    NULL,
    &cparser_node_quit,
    &cparser_node_video_color
};
cparser_node_t cparser_node_breakpoints_list_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_breakpoints_list,
    "List all breakpoints",
    NULL,
    NULL
};
cparser_node_t cparser_node_breakpoints_list = {
    CPARSER_NODE_KEYWORD,
    0,
    "list",
    NULL,
    NULL,
    &cparser_node_breakpoints_list_eol
};
cparser_node_t cparser_node_breakpoints_remove_adress_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_breakpoints_remove_adress,
    "Remove a breakpoint",
    NULL,
    NULL
};
cparser_node_t cparser_node_breakpoints_remove_adress = {
    CPARSER_NODE_HEX,
    0,
    "<HEX:adress>",
    NULL,
    NULL,
    &cparser_node_breakpoints_remove_adress_eol
};
cparser_node_t cparser_node_breakpoints_remove = {
    CPARSER_NODE_KEYWORD,
    0,
    "remove",
    NULL,
    &cparser_node_breakpoints_list,
    &cparser_node_breakpoints_remove_adress
};
cparser_node_t cparser_node_breakpoints_add_adress_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_breakpoints_add_adress,
    "Add a breakpoint in the memory",
    NULL,
    NULL
};
cparser_node_t cparser_node_breakpoints_add_adress = {
    CPARSER_NODE_HEX,
    0,
    "<HEX:adress>",
    NULL,
    NULL,
    &cparser_node_breakpoints_add_adress_eol
};
cparser_node_t cparser_node_breakpoints_add = {
    CPARSER_NODE_KEYWORD,
    0,
    "add",
    NULL,
    &cparser_node_breakpoints_remove,
    &cparser_node_breakpoints_add_adress
};
cparser_node_t cparser_node_breakpoints = {
    CPARSER_NODE_KEYWORD,
    0,
    "breakpoints",
    NULL,
    &cparser_node_video,
    &cparser_node_breakpoints_add
};
cparser_node_t cparser_node_show_registers_z80_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_registers_z80,
    "List Z80 registers",
    NULL,
    NULL
};
cparser_node_t cparser_node_show_registers_z80 = {
    CPARSER_NODE_KEYWORD,
    0,
    "z80",
    NULL,
    NULL,
    &cparser_node_show_registers_z80_eol
};
cparser_node_t cparser_node_show_registers_ga_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_registers_ga,
    "List GA registers values",
    NULL,
    NULL
};
cparser_node_t cparser_node_show_registers_ga = {
    CPARSER_NODE_KEYWORD,
    0,
    "ga",
    NULL,
    &cparser_node_show_registers_z80,
    &cparser_node_show_registers_ga_eol
};
cparser_node_t cparser_node_show_registers_crtc_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_registers_crtc,
    "List CRTC registers values",
    NULL,
    NULL
};
cparser_node_t cparser_node_show_registers_crtc = {
    CPARSER_NODE_KEYWORD,
    0,
    "crtc",
    NULL,
    &cparser_node_show_registers_ga,
    &cparser_node_show_registers_crtc_eol
};
cparser_node_t cparser_node_show_registers_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_registers,
    "List registers values",
    &cparser_node_show_registers_crtc,
    NULL
};
cparser_node_t cparser_node_show_registers = {
    CPARSER_NODE_KEYWORD,
    0,
    "registers",
    NULL,
    NULL,
    &cparser_node_show_registers_eol
};
cparser_node_t cparser_node_show = {
    CPARSER_NODE_KEYWORD,
    0,
    "show",
    NULL,
    &cparser_node_breakpoints,
    &cparser_node_show_registers
};
cparser_node_t cparser_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root node of the parser tree",
    NULL,
    &cparser_node_show
};
