/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#ifndef __CPARSER_TREE_H__
#define __CPARSER_TREE_H__

extern cparser_node_t cparser_root;

cparser_result_t cparser_cmd_show_registers(cparser_context_t *context);
cparser_result_t cparser_cmd_show_registers_crtc(cparser_context_t *context);
cparser_result_t cparser_cmd_show_registers_ga(cparser_context_t *context);
cparser_result_t cparser_cmd_show_registers_z80(cparser_context_t *context);
cparser_result_t cparser_cmd_breakpoints_add_adress(cparser_context_t *context,
    uint32_t *adress_ptr);
cparser_result_t cparser_cmd_breakpoints_remove_adress(cparser_context_t *context,
    uint32_t *adress_ptr);
cparser_result_t cparser_cmd_breakpoints_list(cparser_context_t *context);
cparser_result_t cparser_cmd_video_color_on(cparser_context_t *context);
cparser_result_t cparser_cmd_video_color_gray(cparser_context_t *context);
cparser_result_t cparser_cmd_video_color_green(cparser_context_t *context);
cparser_result_t cparser_cmd_quit(cparser_context_t *context);
cparser_result_t cparser_cmd_reset(cparser_context_t *context);

#endif /* __CPARSER_TREE_H__ */
