#ifndef __DiscEditor__
#define __DiscEditor__

/**
@file
Subclass of DiscEditor, which is generated by wxFormBuilder.
*/

#include "CapriceUI.h"

/** Implementing DiscEditor */
class DiscEditorImpl : public DiscEditor
{
public:
	/** Constructor */
	DiscEditorImpl( wxWindow* parent );
};

#endif // __DiscEditor__
